# =============================================================================================================
# append_loop_info.py
# -------------------------------------------------------------------------------------------------------------
# This python script appends the dislocation loop information generated by loop_info.py to elem_****.vtk files.
# By the addition of the loop information to the elem_****.vtk files, the dislocation loop can be visualized
# by colors in ParaView.
# -------------------------------------------------------------------------------------------------------------
# Developer: A. Takahashi (Tokyo University of Science)
# =============================================================================================================

import os
from pathlib import Path


class LoopData:
    """Class to read loop data from text file and append SCALARS to a VTK file."""

    def __init__(self):
        self.n_elements = 0
        self.loops = []

    def read(self, step):
        """Read loop data from loop_XXXX.txt."""
        filepath = Path(f"loop_{step:04}.txt")
        if not filepath.exists():
            raise FileNotFoundError(f"{filepath} not found.")

        with filepath.open("r") as f:
            lines = [line.strip() for line in f if line.strip()]

        index = 0

        # Skip open loops section
        n_open_loops = int(lines[index].split()[1])
        index += n_open_loops + 1

        # Skip close loops section
        n_close_loops = int(lines[index].split()[1])
        index += n_close_loops + 1

        # Number of loop elements
        self.n_elements = int(lines[index].split()[0])
        index += 1

        # Read loop IDs
        self.loops = [int(lines[index + i].split()[0]) for i in range(self.n_elements)]

    def append(self, step):
        """Append SCALARS LoopID field to elem_XXXX.vtk."""
        vtk_path = Path(f"elem_{step:04}.vtk")
        if not vtk_path.exists():
            raise FileNotFoundError(f"{vtk_path} does not exist.")

        with vtk_path.open("a") as f:
            f.write("\nSCALARS LoopID int\n")
            f.write("LOOKUP_TABLE default\n")
            for loop_id in self.loops:
                f.write(f"{loop_id}\n")


def main():
    step = 1
    while True:
        loop_file = Path(f"loop_{step:04}.txt")

        if not loop_file.exists():
            print(f"No more loop files. Finished at step {step-1}.")
            break

        try:
            loop_data = LoopData()
            loop_data.read(step)
            loop_data.append(step)
            print(f"Processed step {step:04}")
        except Exception as e:
            print(f"Error at step {step:04}: {e}")
            break

        step += 1


if __name__ == "__main__":
    main()
