//===============================================================================
// incstrgen: Calculation of internal stress of inclusions at grid points
//-------------------------------------------------------------------------------
// This code calculates the internal stress of inclusions at grid points using
// the analytical solutions. The output file is designed to use in Element-based
// PDD code.
//-------------------------------------------------------------------------------
// The supported inclusion types are:
// - Spherical
// - Cylindrical
// - Cylindrical (Uniaxial eigen strain)
// - Cuboidal
// - Truncated sphere
//-------------------------------------------------------------------------------
// The input file for this code can be easily generated by using a python
// script. The script named inputgen.py is placed at Tools folder.
//-------------------------------------------------------------------------------
// The code is parallelized with two-ways:
// 1. OpenMP: To enable shared memory-type parallelization, please add options 
// in the compilation
// 2. MPI: To enable distributed memory-type parallelization, please activate
// "DFLAGS" in Makefile. 
//-------------------------------------------------------------------------------
// Developer: A. Takahashi (Tokyo University of Science)
//===============================================================================

#include <stdio.h>

#include "incstr_elliptic.h"
#include "incstr_periodic.h"
#include "incstr_read.h"
#include "incstr_stress.h"
#include "incstr_struct.h"
#include "incstr_write.h"

#ifdef _OPENMP
#include <omp.h>
#endif

int main(int argc, char **argv) {
  INCLUSION_t inclusion;
  GRID_CELL_t grid_cell;
  MATERIAL_t material;

  if (argc != 2) {
    fprintf(stderr, "Usage: %s <working_directory>\n", argv[0]);
    return 1;
  }

#ifdef _OPENMP
  omp_set_num_threads(8);
#endif

  // Read all input data
  INCSTR_ReadInclusions(&inclusion, argv[1]);
  INCSTR_ReadMaterial(&material, argv[1]);
  INCSTR_ReadGrids(&grid_cell, &material, argv[1]);
 
  // Make numerical table for elliptical integral.
  INCSTR_MakeEllipticIntegralTable();
  // Image cells are prepared to apply the periodic boundary condition
  INCSTR_MakePeriodicImages(&material);

  // Calculate the internal stress of inclusions
  INCSTR_InclusionStress(&inclusion, &material, &grid_cell);

  // Output the calculated internal stress of inclusions
  INCSTR_WriteStress(&grid_cell, argv[1]);

  return 0;
}